### ISSUE TITLE
Unmet peer dependency?

### ISSUE THREAD

**Issue by perfectra1n** [illl48/RobInDaHood#5]
No native production dependencies
ROBINDAHOOD@0.0.1 C:\filepath
+-- node-notifier@5.1.2
+-- react-scripts@0.9.5
| `-- jest@18.1.0
|   `-- jest-cli@18.1.0
|     `-- node-notifier@4.6.1
`-- UNMET PEER DEPENDENCY react-tap-event-plugin@^2.0.1

Any idea what may be the issue?

**Comment by perfectra1n** [comment]
I also get these warnings when I'm in developer mode - it just simply shows the loading screen, nothing more.

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning @ bundle.js:11963
bundle.js:40921 Uncaught TypeError: Cannot read property 'symbol' of undefined
    at http://localhost:5000/static/js/bundle.js:40921:47
    at Array.map (native)
    at http://localhost:5000/static/js/bundle.js:40918:15
    at Array.forEach (native)
    at DashboardPage.render (http://localhost:5000/static/js/bundle.js:40910:26)
    at http://localhost:5000/static/js/bundle.js:27030:22
    at measureLifeCyclePerf (http://localhost:5000/static/js/bundle.js:26309:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:5000/static/js/bundle.js:27029:26)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:5000/static/js/bundle.js:27056:33)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:5000/static/js/bundle.js:26596:31)

**Comment by edwardlai3582** [comment]
Sorry for the inconvenience
have you tried the current code?
And maybe delete all the data in localstorage. (i'm still refactorin the code so the things i stored in localstorage might changed)

**Comment by perfectra1n** [comment]
No worries, still learning as well. Yes, it does, even with a fresh install of code.

**Comment by perfectra1n** [comment]
If I force it to react-tap-event-plugin@~2.0.1 it simply shows the loading screen.

**Comment by edwardlai3582** [comment]
react-tap-event-plugin@~2.0.1 is not the reason (its a package needed by other packages to support touch screen tap event, you can npm install --save react-tap-event-plugin@~2.0.1 if you want )

maybe try to 1. click help on the top left corner, click toggle dev tools 2. click Application 3. click Localstorage, click file:// 4. delete all the key/value pairs by selectin them and press delete 5. click help, click Reload http://imgur.com/a/5blKM

**Comment by perfectra1n** [comment]
Awesome, got it. Yes, that npm command is the one i did try to run ~

I didn't end up having to clear the local storage, when I did a fresh compile of the brand new code, even though it spit that error at me, it worked. Thanks for all your help, love the app.
